#!/bin/bash

echo "Kurulum için yönetici şifresini giriniz."

sudo apt-get install -y python3-pip
 
sudo pip3 install --upgrade pip

sudo pip3 install reportlab

sudo pip3 install -U pip setuptools

sudo pip3 install pillow

sudo apt-get install evince

sudo apt-get install font-manager

exec font-manager TTKBDikTemelAbece.ttf

